from collections.abc import Sequence
from typing import Any, Protocol


class DbCursor(Protocol):
    def execute(self, sql: str, params: tuple[Any, ...] = ()) -> "DbCursor": ...
    def executemany(self, sql: str, params_list: Sequence[tuple[Any, ...]]) -> None: ...
    def fetchone(self) -> Any: ...
    def fetchall(self) -> list[Any]: ...
    @property
    def description(self) -> Any: ...


class DbConnection(Protocol):
    def cursor(self) -> DbCursor: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
